# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: woot5
version: '0.0.0'
github: "NicolasKeita/woot5"
license: MIT
author: "NicolasKeita"
maintainer: "NicolasKeita"
# synopsis: A new Haskeleton package.
# description: woot5 is a new Haskeleton package.
# category: Other

extra-source-files:
- package.yaml
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  woot5:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - woot5
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  woot5-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - woot5
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  woot5-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - woot5
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
